//! Generate mdBook catalog pages from the embedded reference corpus.

use std::fs;
use std::path::{Path, PathBuf};

use spice_parser::Dialect;

use crate::{ReferenceEntry, ReferenceIndex};

/// Whether to write files or only check they match.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CatalogMode {
    Write,
    Check,
}

const GENERATED_BANNER: &str = "<!-- Generated by `pixi run reference-docs`. Do not edit by hand. -->\n";

/// Render one dialect's effective catalog (shared + overlays) as Markdown.
pub fn render_dialect_catalog(index: &ReferenceIndex, dialect: Dialect) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BANNER);
    out.push_str(&format!(
        "# {} reference catalog\n\n",
        dialect.label()
    ));
    out.push_str(&format!(
        "Effective documentation for the **{}** dialect (`spiceLsp.dialect = \"{}\"`): shared entries plus dialect overlays.\n\n",
        dialect.label(),
        dialect.id()
    ));
    out.push_str("Source of truth: JSON under [`reference/`](../../reference/). Hover in the editor uses the same corpus.\n\n");

    let entries = index.effective_entries(dialect);
    let directives: Vec<_> = entries
        .iter()
        .filter(|(_, e)| e.kind == "directive")
        .copied()
        .collect();
    let elements: Vec<_> = entries
        .iter()
        .filter(|(_, e)| e.kind == "element")
        .copied()
        .collect();
    let other: Vec<_> = entries
        .iter()
        .filter(|(_, e)| e.kind != "directive" && e.kind != "element")
        .copied()
        .collect();

    out.push_str("## Index\n\n");
    out.push_str("| Name | Kind | Summary | Source |\n");
    out.push_str("|------|------|---------|--------|\n");
    for (overridden, entry) in &entries {
        let source = if *overridden { "dialect" } else { "shared" };
        out.push_str(&format!(
            "| [`{}`](#{}) | {} | {} | {} |\n",
            entry.name,
            anchor(&entry.name),
            entry.kind,
            escape_cells(&entry.summary),
            source
        ));
    }
    out.push('\n');

    append_section(&mut out, "Directives", &directives);
    append_section(&mut out, "Elements", &elements);
    if !other.is_empty() {
        append_section(&mut out, "Other", &other);
    }

    out
}

fn render_shared_catalog(index: &ReferenceIndex) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BANNER);
    out.push_str("# Shared reference catalog\n\n");
    out.push_str("Constructs common to all dialects. Dialect pages overlay these when a matching `(kind, name)` exists.\n\n");
    out.push_str("Source of truth: [`reference/_shared/`](../../reference/_shared/).\n\n");

    let entries = index.shared_entries();
    out.push_str("## Index\n\n");
    out.push_str("| Name | Kind | Summary |\n");
    out.push_str("|------|------|--------|\n");
    for entry in &entries {
        out.push_str(&format!(
            "| [`{}`](#{}) | {} | {} |\n",
            entry.name,
            anchor(&entry.name),
            entry.kind,
            escape_cells(&entry.summary)
        ));
    }
    out.push('\n');

    let tagged: Vec<(bool, &ReferenceEntry)> =
        entries.into_iter().map(|e| (false, e)).collect();
    let directives: Vec<_> = tagged
        .iter()
        .filter(|(_, e)| e.kind == "directive")
        .copied()
        .collect();
    let elements: Vec<_> = tagged
        .iter()
        .filter(|(_, e)| e.kind == "element")
        .copied()
        .collect();

    append_section(&mut out, "Directives", &directives);
    append_section(&mut out, "Elements", &elements);
    out
}

fn render_index_page(index: &ReferenceIndex) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BANNER);
    out.push_str("# Dialect reference catalog\n\n");
    out.push_str("This section is **generated** from the curated JSON corpus under `reference/`.\n");
    out.push_str("The language server embeds the same data for hover (and later completion docs).\n\n");
    out.push_str("## How to update\n\n");
    out.push_str("1. Edit or add JSON under `reference/_shared/` or `reference/<dialect>/`.\n");
    out.push_str("2. Run `pixi run reference-validate`.\n");
    out.push_str("3. Run `pixi run reference-docs` to regenerate these pages.\n");
    out.push_str("4. CI runs `pixi run reference-docs-check` so the book stays in sync.\n\n");
    out.push_str("Design notes: [Multi-dialect support](../internal/2_multi-dialect-design.md).\n\n");
    out.push_str("## Dialects\n\n");
    out.push_str("| Dialect | Setting value | Entries (effective) | Catalog |\n");
    out.push_str("|---------|---------------|---------------------|--------|\n");
    out.push_str(&format!(
        "| Shared base | — | {} | [Shared](1_shared.md) |\n",
        index.shared_entries().len()
    ));
    for dialect in Dialect::ALL {
        let n = index.effective_entries(dialect).len();
        let file = match dialect {
            Dialect::Hspice => "2_hspice.md",
            Dialect::Ngspice => "3_ngspice.md",
            Dialect::Ltspice => "4_ltspice.md",
        };
        out.push_str(&format!(
            "| {} | `{}` | {} | [{}]({}) |\n",
            dialect.label(),
            dialect.id(),
            n,
            dialect.label(),
            file
        ));
    }
    out.push('\n');
    out.push_str(&format!(
        "_Embedded corpus size: {} raw JSON entries (shared + overlays)._\n",
        index.len()
    ));
    out
}

fn append_section(out: &mut String, title: &str, entries: &[(bool, &ReferenceEntry)]) {
    if entries.is_empty() {
        return;
    }
    out.push_str(&format!("## {title}\n\n"));
    for (overridden, entry) in entries {
        out.push_str(&format!("### {}\n\n", entry.name));
        out.push_str(&format!("**{}** — {}\n\n", entry.id, entry.summary));
        if *overridden {
            out.push_str("_Dialect overlay (replaces shared entry with the same name)._\n\n");
        }
        out.push_str("```\n");
        out.push_str(&entry.syntax);
        out.push_str("\n```\n\n");

        if !entry.parameters.is_empty() {
            out.push_str("| Parameter | Description | Units |\n");
            out.push_str("|-----------|-------------|-------|\n");
            for p in &entry.parameters {
                out.push_str(&format!(
                    "| `{}` | {} | {} |\n",
                    p.name,
                    escape_cells(&p.description),
                    p.units.as_deref().unwrap_or("")
                ));
            }
            out.push('\n');
        }

        if !entry.examples.is_empty() {
            out.push_str("**Examples**\n\n");
            for ex in &entry.examples {
                out.push_str(&format!("- `{}`\n", ex));
            }
            out.push('\n');
        }

        if let Some(notes) = &entry.dialect_notes {
            out.push_str(&format!("_{notes}_\n\n"));
        }

        if !entry.see_also.is_empty() {
            out.push_str("**See also:** ");
            out.push_str(
                &entry
                    .see_also
                    .iter()
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", "),
            );
            out.push_str("\n\n");
        }
    }
}

fn escape_cells(s: &str) -> String {
    s.replace('|', "\\|")
}

fn anchor(name: &str) -> String {
    name.trim()
        .trim_start_matches('.')
        .to_ascii_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect()
}

fn catalog_outputs(docs_reference_dir: &Path) -> Vec<(PathBuf, String)> {
    let index = ReferenceIndex::load_embedded();
    vec![
        (
            docs_reference_dir.join("README.md"),
            render_index_page(&index),
        ),
        (
            docs_reference_dir.join("1_shared.md"),
            render_shared_catalog(&index),
        ),
        (
            docs_reference_dir.join("2_hspice.md"),
            render_dialect_catalog(&index, Dialect::Hspice),
        ),
        (
            docs_reference_dir.join("3_ngspice.md"),
            render_dialect_catalog(&index, Dialect::Ngspice),
        ),
        (
            docs_reference_dir.join("4_ltspice.md"),
            render_dialect_catalog(&index, Dialect::Ltspice),
        ),
    ]
}

/// Write or verify generated catalog pages under `docs/reference/`.
pub fn generate_catalog_files(repo_root: &Path, mode: CatalogMode) -> Result<(), String> {
    let out_dir = repo_root.join("docs/reference");
    fs::create_dir_all(&out_dir).map_err(|e| format!("mkdir {}: {e}", out_dir.display()))?;

    let outputs = catalog_outputs(&out_dir);
    match mode {
        CatalogMode::Write => {
            for (path, content) in outputs {
                fs::write(&path, content)
                    .map_err(|e| format!("write {}: {e}", path.display()))?;
                eprintln!("wrote {}", path.display());
            }
            Ok(())
        }
        CatalogMode::Check => {
            let mut mismatches = Vec::new();
            for (path, expected) in outputs {
                let actual = fs::read_to_string(&path).unwrap_or_default();
                if actual != expected {
                    mismatches.push(path.display().to_string());
                }
            }
            if mismatches.is_empty() {
                eprintln!("reference catalog docs are up to date");
                Ok(())
            } else {
                Err(format!(
                    "reference catalog out of date:\n  {}\nRun: pixi run reference-docs",
                    mismatches.join("\n  ")
                ))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use spice_parser::Dialect;

    #[test]
    fn dialect_catalog_mentions_overlay_and_shared() {
        let index = ReferenceIndex::load_embedded();
        let md = render_dialect_catalog(&index, Dialect::Hspice);
        assert!(md.contains("HSPICE reference catalog"));
        assert!(md.contains(".tran") || md.contains("tran"));
        assert!(md.contains("Generated by"));
    }

    #[test]
    fn shared_catalog_non_empty() {
        let index = ReferenceIndex::load_embedded();
        let md = render_shared_catalog(&index);
        assert!(md.contains("Shared reference catalog"));
        assert!(!index.shared_entries().is_empty());
    }
}
